//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Music {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Music.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T002.
        /// </summary>
        public static string AlbumImageId {
            get {
                return ResourceManager.GetString("AlbumImageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,w,v,x,y,z.
        /// </summary>
        public static string Alphabet {
            get {
                return ResourceManager.GetString("Alphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIzaSyAD91OiEeWRoqhsw0peq94qg5joZe47r_s.
        /// </summary>
        public static string ApiKey {
            get {
                return ResourceManager.GetString("ApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T001.
        /// </summary>
        public static string ArtistImageId {
            get {
                return ResourceManager.GetString("ArtistImageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a,á,à,ả,ã,ạ,ă,ắ,ằ,ẳ,ẵ,ặ,â,ấ,ầ,ẩ,ẫ,ậ.
        /// </summary>
        public static string CharactersA {
            get {
                return ResourceManager.GetString("CharactersA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d,đ.
        /// </summary>
        public static string CharactersD {
            get {
                return ResourceManager.GetString("CharactersD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e,é,è,ẻ,ẽ,ẹ,ê,ế,ề,ể,ễ,ệ.
        /// </summary>
        public static string CharactersE {
            get {
                return ResourceManager.GetString("CharactersE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to o,ó,ò,ỏ,õ,ọ,ô,ố,ồ,ổ,ỗ,ộ,ơ,ớ,ờ,ở,ỡ,ợ.
        /// </summary>
        public static string CharactersO {
            get {
                return ResourceManager.GetString("CharactersO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to u,ú,ù,ủ,ũ,ụ,ư,ứ,ừ,ử,ữ,ự.
        /// </summary>
        public static string CharactersU {
            get {
                return ResourceManager.GetString("CharactersU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .jpg.
        /// </summary>
        public static string ImageExtension {
            get {
                return ResourceManager.GetString("ImageExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://y.gtimg.cn/music/photo_new/.
        /// </summary>
        public static string ImageServerUrl {
            get {
                return ResourceManager.GetString("ImageServerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,1,2,3,4,5,6,7,8,9.
        /// </summary>
        public static string NumberCharacters {
            get {
                return ResourceManager.GetString("NumberCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1znQOtTDJz0UqDs0uB2MQZV3wN0l_J0TrU44d9chH2SI.
        /// </summary>
        public static string SpreadsheetId {
            get {
                return ResourceManager.GetString("SpreadsheetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://img.youtube.com/vi/.
        /// </summary>
        public static string VideoImageUrl {
            get {
                return ResourceManager.GetString("VideoImageUrl", resourceCulture);
            }
        }
    }
}
